language: csharp
solution: O365-APIs-Start-ASPNET-MVC.sln
install:
  - nuget restore O365-APIs-Start-ASPNET-MVC.sln -verbosity detailed
mono: 
  - latest
script:
  - xbuild /p:Configuration=Debug O365-APIs-Start-ASPNET-MVC.sln